/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Id = IDL.Nat;
export const BookingStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const Booking = IDL.Record({
  'id' : Id,
  'status' : BookingStatus,
  'stayId' : IDL.Opt(Id),
  'paymentStatus' : IDL.Text,
  'trekId' : IDL.Opt(Id),
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'travelDates' : IDL.Text,
  'email' : IDL.Text,
  'razorpaySignature' : IDL.Opt(IDL.Text),
  'yatraId' : IDL.Opt(Id),
  'razorpayOrderId' : IDL.Opt(IDL.Text),
  'paymentId' : IDL.Opt(IDL.Text),
  'amountINR' : IDL.Nat,
  'phone' : IDL.Text,
  'groupSize' : IDL.Nat,
  'packageId' : IDL.Opt(Id),
});
export const BookingInput = IDL.Record({
  'stayId' : IDL.Opt(Id),
  'trekId' : IDL.Opt(Id),
  'name' : IDL.Text,
  'travelDates' : IDL.Text,
  'email' : IDL.Text,
  'yatraId' : IDL.Opt(Id),
  'amountINR' : IDL.Nat,
  'phone' : IDL.Text,
  'groupSize' : IDL.Nat,
  'packageId' : IDL.Opt(Id),
});
export const RazorpayOrderResult = IDL.Record({
  'orderId' : IDL.Text,
  'currency' : IDL.Text,
  'amount' : IDL.Nat,
  'keyId' : IDL.Text,
});
export const BookingWithPaymentResult = IDL.Record({
  'bookingId' : IDL.Text,
  'razorpayOrder' : RazorpayOrderResult,
});
export const Slug = IDL.Text;
export const BlogPost = IDL.Record({
  'id' : Id,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'readTimeMin' : IDL.Nat,
  'slug' : Slug,
  'authorName' : IDL.Text,
  'publishedAt' : Timestamp,
  'readTime' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'excerpt' : IDL.Text,
  'category' : IDL.Text,
});
export const PackageTier = IDL.Record({
  'name' : IDL.Text,
  'pricePerPerson' : IDL.Nat,
});
export const PriceRange = IDL.Record({
  'minINR' : IDL.Nat,
  'maxINR' : IDL.Nat,
});
export const DayItinerary = IDL.Record({
  'day' : IDL.Nat,
  'endAltitudeM' : IDL.Nat,
  'title' : IDL.Text,
  'startAltitudeM' : IDL.Nat,
  'campsite' : IDL.Text,
  'difficulty' : IDL.Text,
  'description' : IDL.Text,
  'landmarks' : IDL.Vec(IDL.Text),
  'distanceKm' : IDL.Float64,
  'mealsIncluded' : IDL.Text,
  'route' : IDL.Text,
});
export const Package = IDL.Record({
  'id' : Id,
  'tiers' : IDL.Vec(PackageTier),
  'duration' : IDL.Text,
  'accommodationType' : IDL.Text,
  'name' : IDL.Text,
  'slug' : Slug,
  'description' : IDL.Text,
  'inclusions' : IDL.Vec(IDL.Text),
  'priceRange' : PriceRange,
  'imageUrl' : IDL.Text,
  'groupSizeMax' : IDL.Nat,
  'exclusions' : IDL.Vec(IDL.Text),
  'category' : IDL.Text,
  'groupSize' : IDL.Text,
  'itinerary' : IDL.Vec(DayItinerary),
  'problemSolved' : IDL.Text,
});
export const Stay = IDL.Record({
  'id' : Id,
  'nearbyAttractions' : IDL.Vec(IDL.Text),
  'ownerNote' : IDL.Text,
  'pricePerNightMax' : IDL.Nat,
  'pricePerNightMin' : IDL.Nat,
  'stayType' : IDL.Text,
  'name' : IDL.Text,
  'slug' : Slug,
  'description' : IDL.Text,
  'amenities' : IDL.Vec(IDL.Text),
  'imageUrl' : IDL.Text,
  'location' : IDL.Text,
});
export const Trek = IDL.Record({
  'id' : Id,
  'region' : IDL.Text,
  'durationDays' : IDL.Nat,
  'durationNights' : IDL.Nat,
  'difficulty' : IDL.Text,
  'name' : IDL.Text,
  'slug' : Slug,
  'description' : IDL.Text,
  'inclusions' : IDL.Vec(IDL.Text),
  'highlights' : IDL.Vec(IDL.Text),
  'priceRange' : PriceRange,
  'state' : IDL.Text,
  'imageUrl' : IDL.Text,
  'distanceKm' : IDL.Float64,
  'maxAltitudeM' : IDL.Nat,
  'exclusions' : IDL.Vec(IDL.Text),
  'category' : IDL.Text,
  'endPoint' : IDL.Text,
  'maxAltitudeFt' : IDL.Nat,
  'startPoint' : IDL.Text,
  'itinerary' : IDL.Vec(DayItinerary),
  'bestSeason' : IDL.Text,
});
export const Yatra = IDL.Record({
  'id' : Id,
  'spiritualSignificance' : IDL.Text,
  'duration' : IDL.Text,
  'helicopterInfo' : IDL.Opt(IDL.Text),
  'temples' : IDL.Vec(IDL.Text),
  'registration' : IDL.Text,
  'name' : IDL.Text,
  'slug' : Slug,
  'description' : IDL.Text,
  'season' : IDL.Text,
  'priceRange' : PriceRange,
  'permits' : IDL.Text,
  'imageUrl' : IDL.Text,
  'pujaGuide' : IDL.Text,
  'templeTimings' : IDL.Text,
  'registrationInfo' : IDL.Text,
  'itinerary' : IDL.Vec(DayItinerary),
  'route' : IDL.Text,
  'accessibility' : IDL.Text,
});
export const SearchResults = IDL.Record({
  'treks' : IDL.Vec(Trek),
  'packages' : IDL.Vec(Package),
  'blogPosts' : IDL.Vec(BlogPost),
  'stays' : IDL.Vec(Stay),
  'yatras' : IDL.Vec(Yatra),
});

export const idlService = IDL.Service({
  'confirmBookingPayment' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Opt(Booking)],
      [],
    ),
  'createBooking' : IDL.Func([BookingInput], [Booking], []),
  'createBookingWithPayment' : IDL.Func(
      [BookingInput],
      [BookingWithPaymentResult],
      [],
    ),
  'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getAllPackages' : IDL.Func([], [IDL.Vec(Package)], ['query']),
  'getAllStays' : IDL.Func([], [IDL.Vec(Stay)], ['query']),
  'getAllTreks' : IDL.Func([], [IDL.Vec(Trek)], ['query']),
  'getAllYatras' : IDL.Func([], [IDL.Vec(Yatra)], ['query']),
  'getBlogPostBySlug' : IDL.Func([IDL.Text], [IDL.Opt(BlogPost)], ['query']),
  'getPackageBySlug' : IDL.Func([IDL.Text], [IDL.Opt(Package)], ['query']),
  'getStayBySlug' : IDL.Func([IDL.Text], [IDL.Opt(Stay)], ['query']),
  'getTrekBySlug' : IDL.Func([IDL.Text], [IDL.Opt(Trek)], ['query']),
  'getTreksByDifficulty' : IDL.Func([IDL.Text], [IDL.Vec(Trek)], ['query']),
  'getTreksByState' : IDL.Func([IDL.Text], [IDL.Vec(Trek)], ['query']),
  'getUserBookings' : IDL.Func([IDL.Text], [IDL.Vec(Booking)], ['query']),
  'getYatraBySlug' : IDL.Func([IDL.Text], [IDL.Opt(Yatra)], ['query']),
  'searchAll' : IDL.Func([IDL.Text], [SearchResults], ['query']),
  'searchTreks' : IDL.Func([IDL.Text], [IDL.Vec(Trek)], ['query']),
  'setRazorpayKeys' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Id = IDL.Nat;
  const BookingStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const Booking = IDL.Record({
    'id' : Id,
    'status' : BookingStatus,
    'stayId' : IDL.Opt(Id),
    'paymentStatus' : IDL.Text,
    'trekId' : IDL.Opt(Id),
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'travelDates' : IDL.Text,
    'email' : IDL.Text,
    'razorpaySignature' : IDL.Opt(IDL.Text),
    'yatraId' : IDL.Opt(Id),
    'razorpayOrderId' : IDL.Opt(IDL.Text),
    'paymentId' : IDL.Opt(IDL.Text),
    'amountINR' : IDL.Nat,
    'phone' : IDL.Text,
    'groupSize' : IDL.Nat,
    'packageId' : IDL.Opt(Id),
  });
  const BookingInput = IDL.Record({
    'stayId' : IDL.Opt(Id),
    'trekId' : IDL.Opt(Id),
    'name' : IDL.Text,
    'travelDates' : IDL.Text,
    'email' : IDL.Text,
    'yatraId' : IDL.Opt(Id),
    'amountINR' : IDL.Nat,
    'phone' : IDL.Text,
    'groupSize' : IDL.Nat,
    'packageId' : IDL.Opt(Id),
  });
  const RazorpayOrderResult = IDL.Record({
    'orderId' : IDL.Text,
    'currency' : IDL.Text,
    'amount' : IDL.Nat,
    'keyId' : IDL.Text,
  });
  const BookingWithPaymentResult = IDL.Record({
    'bookingId' : IDL.Text,
    'razorpayOrder' : RazorpayOrderResult,
  });
  const Slug = IDL.Text;
  const BlogPost = IDL.Record({
    'id' : Id,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'readTimeMin' : IDL.Nat,
    'slug' : Slug,
    'authorName' : IDL.Text,
    'publishedAt' : Timestamp,
    'readTime' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'excerpt' : IDL.Text,
    'category' : IDL.Text,
  });
  const PackageTier = IDL.Record({
    'name' : IDL.Text,
    'pricePerPerson' : IDL.Nat,
  });
  const PriceRange = IDL.Record({ 'minINR' : IDL.Nat, 'maxINR' : IDL.Nat });
  const DayItinerary = IDL.Record({
    'day' : IDL.Nat,
    'endAltitudeM' : IDL.Nat,
    'title' : IDL.Text,
    'startAltitudeM' : IDL.Nat,
    'campsite' : IDL.Text,
    'difficulty' : IDL.Text,
    'description' : IDL.Text,
    'landmarks' : IDL.Vec(IDL.Text),
    'distanceKm' : IDL.Float64,
    'mealsIncluded' : IDL.Text,
    'route' : IDL.Text,
  });
  const Package = IDL.Record({
    'id' : Id,
    'tiers' : IDL.Vec(PackageTier),
    'duration' : IDL.Text,
    'accommodationType' : IDL.Text,
    'name' : IDL.Text,
    'slug' : Slug,
    'description' : IDL.Text,
    'inclusions' : IDL.Vec(IDL.Text),
    'priceRange' : PriceRange,
    'imageUrl' : IDL.Text,
    'groupSizeMax' : IDL.Nat,
    'exclusions' : IDL.Vec(IDL.Text),
    'category' : IDL.Text,
    'groupSize' : IDL.Text,
    'itinerary' : IDL.Vec(DayItinerary),
    'problemSolved' : IDL.Text,
  });
  const Stay = IDL.Record({
    'id' : Id,
    'nearbyAttractions' : IDL.Vec(IDL.Text),
    'ownerNote' : IDL.Text,
    'pricePerNightMax' : IDL.Nat,
    'pricePerNightMin' : IDL.Nat,
    'stayType' : IDL.Text,
    'name' : IDL.Text,
    'slug' : Slug,
    'description' : IDL.Text,
    'amenities' : IDL.Vec(IDL.Text),
    'imageUrl' : IDL.Text,
    'location' : IDL.Text,
  });
  const Trek = IDL.Record({
    'id' : Id,
    'region' : IDL.Text,
    'durationDays' : IDL.Nat,
    'durationNights' : IDL.Nat,
    'difficulty' : IDL.Text,
    'name' : IDL.Text,
    'slug' : Slug,
    'description' : IDL.Text,
    'inclusions' : IDL.Vec(IDL.Text),
    'highlights' : IDL.Vec(IDL.Text),
    'priceRange' : PriceRange,
    'state' : IDL.Text,
    'imageUrl' : IDL.Text,
    'distanceKm' : IDL.Float64,
    'maxAltitudeM' : IDL.Nat,
    'exclusions' : IDL.Vec(IDL.Text),
    'category' : IDL.Text,
    'endPoint' : IDL.Text,
    'maxAltitudeFt' : IDL.Nat,
    'startPoint' : IDL.Text,
    'itinerary' : IDL.Vec(DayItinerary),
    'bestSeason' : IDL.Text,
  });
  const Yatra = IDL.Record({
    'id' : Id,
    'spiritualSignificance' : IDL.Text,
    'duration' : IDL.Text,
    'helicopterInfo' : IDL.Opt(IDL.Text),
    'temples' : IDL.Vec(IDL.Text),
    'registration' : IDL.Text,
    'name' : IDL.Text,
    'slug' : Slug,
    'description' : IDL.Text,
    'season' : IDL.Text,
    'priceRange' : PriceRange,
    'permits' : IDL.Text,
    'imageUrl' : IDL.Text,
    'pujaGuide' : IDL.Text,
    'templeTimings' : IDL.Text,
    'registrationInfo' : IDL.Text,
    'itinerary' : IDL.Vec(DayItinerary),
    'route' : IDL.Text,
    'accessibility' : IDL.Text,
  });
  const SearchResults = IDL.Record({
    'treks' : IDL.Vec(Trek),
    'packages' : IDL.Vec(Package),
    'blogPosts' : IDL.Vec(BlogPost),
    'stays' : IDL.Vec(Stay),
    'yatras' : IDL.Vec(Yatra),
  });
  
  return IDL.Service({
    'confirmBookingPayment' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Opt(Booking)],
        [],
      ),
    'createBooking' : IDL.Func([BookingInput], [Booking], []),
    'createBookingWithPayment' : IDL.Func(
        [BookingInput],
        [BookingWithPaymentResult],
        [],
      ),
    'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getAllPackages' : IDL.Func([], [IDL.Vec(Package)], ['query']),
    'getAllStays' : IDL.Func([], [IDL.Vec(Stay)], ['query']),
    'getAllTreks' : IDL.Func([], [IDL.Vec(Trek)], ['query']),
    'getAllYatras' : IDL.Func([], [IDL.Vec(Yatra)], ['query']),
    'getBlogPostBySlug' : IDL.Func([IDL.Text], [IDL.Opt(BlogPost)], ['query']),
    'getPackageBySlug' : IDL.Func([IDL.Text], [IDL.Opt(Package)], ['query']),
    'getStayBySlug' : IDL.Func([IDL.Text], [IDL.Opt(Stay)], ['query']),
    'getTrekBySlug' : IDL.Func([IDL.Text], [IDL.Opt(Trek)], ['query']),
    'getTreksByDifficulty' : IDL.Func([IDL.Text], [IDL.Vec(Trek)], ['query']),
    'getTreksByState' : IDL.Func([IDL.Text], [IDL.Vec(Trek)], ['query']),
    'getUserBookings' : IDL.Func([IDL.Text], [IDL.Vec(Booking)], ['query']),
    'getYatraBySlug' : IDL.Func([IDL.Text], [IDL.Opt(Yatra)], ['query']),
    'searchAll' : IDL.Func([IDL.Text], [SearchResults], ['query']),
    'searchTreks' : IDL.Func([IDL.Text], [IDL.Vec(Trek)], ['query']),
    'setRazorpayKeys' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };