/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlogPost {
  'id' : Id,
  'title' : string,
  'content' : string,
  'readTimeMin' : bigint,
  'slug' : Slug,
  'authorName' : string,
  'publishedAt' : Timestamp,
  'readTime' : bigint,
  'imageUrl' : string,
  'excerpt' : string,
  'category' : string,
}
export interface Booking {
  'id' : Id,
  'status' : BookingStatus,
  'stayId' : [] | [Id],
  'paymentStatus' : string,
  'trekId' : [] | [Id],
  'name' : string,
  'createdAt' : Timestamp,
  'travelDates' : string,
  'email' : string,
  'razorpaySignature' : [] | [string],
  'yatraId' : [] | [Id],
  'razorpayOrderId' : [] | [string],
  'paymentId' : [] | [string],
  'amountINR' : bigint,
  'phone' : string,
  'groupSize' : bigint,
  'packageId' : [] | [Id],
}
export interface BookingInput {
  'stayId' : [] | [Id],
  'trekId' : [] | [Id],
  'name' : string,
  'travelDates' : string,
  'email' : string,
  'yatraId' : [] | [Id],
  'amountINR' : bigint,
  'phone' : string,
  'groupSize' : bigint,
  'packageId' : [] | [Id],
}
export type BookingStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'confirmed' : null };
export interface BookingWithPaymentResult {
  'bookingId' : string,
  'razorpayOrder' : RazorpayOrderResult,
}
export interface DayItinerary {
  'day' : bigint,
  'endAltitudeM' : bigint,
  'title' : string,
  'startAltitudeM' : bigint,
  'campsite' : string,
  'difficulty' : string,
  'description' : string,
  'landmarks' : Array<string>,
  'distanceKm' : number,
  'mealsIncluded' : string,
  'route' : string,
}
export type Id = bigint;
export interface Package {
  'id' : Id,
  'tiers' : Array<PackageTier>,
  'duration' : string,
  'accommodationType' : string,
  'name' : string,
  'slug' : Slug,
  'description' : string,
  'inclusions' : Array<string>,
  'priceRange' : PriceRange,
  'imageUrl' : string,
  'groupSizeMax' : bigint,
  'exclusions' : Array<string>,
  'category' : string,
  'groupSize' : string,
  'itinerary' : Array<DayItinerary>,
  'problemSolved' : string,
}
export interface PackageTier { 'name' : string, 'pricePerPerson' : bigint }
export interface PriceRange { 'minINR' : bigint, 'maxINR' : bigint }
export interface RazorpayOrderResult {
  'orderId' : string,
  'currency' : string,
  'amount' : bigint,
  'keyId' : string,
}
export interface SearchResults {
  'treks' : Array<Trek>,
  'packages' : Array<Package>,
  'blogPosts' : Array<BlogPost>,
  'stays' : Array<Stay>,
  'yatras' : Array<Yatra>,
}
export type Slug = string;
export interface Stay {
  'id' : Id,
  'nearbyAttractions' : Array<string>,
  'ownerNote' : string,
  'pricePerNightMax' : bigint,
  'pricePerNightMin' : bigint,
  'stayType' : string,
  'name' : string,
  'slug' : Slug,
  'description' : string,
  'amenities' : Array<string>,
  'imageUrl' : string,
  'location' : string,
}
export type Timestamp = bigint;
export interface Trek {
  'id' : Id,
  'region' : string,
  'durationDays' : bigint,
  'durationNights' : bigint,
  'difficulty' : string,
  'name' : string,
  'slug' : Slug,
  'description' : string,
  'inclusions' : Array<string>,
  'highlights' : Array<string>,
  'priceRange' : PriceRange,
  'state' : string,
  'imageUrl' : string,
  'distanceKm' : number,
  'maxAltitudeM' : bigint,
  'exclusions' : Array<string>,
  'category' : string,
  'endPoint' : string,
  'maxAltitudeFt' : bigint,
  'startPoint' : string,
  'itinerary' : Array<DayItinerary>,
  'bestSeason' : string,
}
export interface Yatra {
  'id' : Id,
  'spiritualSignificance' : string,
  'duration' : string,
  'helicopterInfo' : [] | [string],
  'temples' : Array<string>,
  'registration' : string,
  'name' : string,
  'slug' : Slug,
  'description' : string,
  'season' : string,
  'priceRange' : PriceRange,
  'permits' : string,
  'imageUrl' : string,
  'pujaGuide' : string,
  'templeTimings' : string,
  'registrationInfo' : string,
  'itinerary' : Array<DayItinerary>,
  'route' : string,
  'accessibility' : string,
}
export interface _SERVICE {
  'confirmBookingPayment' : ActorMethod<
    [bigint, string, string],
    [] | [Booking]
  >,
  'createBooking' : ActorMethod<[BookingInput], Booking>,
  'createBookingWithPayment' : ActorMethod<
    [BookingInput],
    BookingWithPaymentResult
  >,
  'getAllBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getAllPackages' : ActorMethod<[], Array<Package>>,
  'getAllStays' : ActorMethod<[], Array<Stay>>,
  'getAllTreks' : ActorMethod<[], Array<Trek>>,
  'getAllYatras' : ActorMethod<[], Array<Yatra>>,
  'getBlogPostBySlug' : ActorMethod<[string], [] | [BlogPost]>,
  'getPackageBySlug' : ActorMethod<[string], [] | [Package]>,
  'getStayBySlug' : ActorMethod<[string], [] | [Stay]>,
  'getTrekBySlug' : ActorMethod<[string], [] | [Trek]>,
  'getTreksByDifficulty' : ActorMethod<[string], Array<Trek>>,
  'getTreksByState' : ActorMethod<[string], Array<Trek>>,
  'getUserBookings' : ActorMethod<[string], Array<Booking>>,
  'getYatraBySlug' : ActorMethod<[string], [] | [Yatra]>,
  'searchAll' : ActorMethod<[string], SearchResults>,
  'searchTreks' : ActorMethod<[string], Array<Trek>>,
  'setRazorpayKeys' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];