/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface BlogPost {
    id: Id;
    title: string;
    content: string;
    readTimeMin: bigint;
    slug: Slug;
    authorName: string;
    publishedAt: Timestamp;
    readTime: bigint;
    imageUrl: string;
    excerpt: string;
    category: string;
}
export type Timestamp = bigint;
export interface DayItinerary {
    day: bigint;
    endAltitudeM: bigint;
    title: string;
    startAltitudeM: bigint;
    campsite: string;
    difficulty: string;
    description: string;
    landmarks: Array<string>;
    distanceKm: number;
    mealsIncluded: string;
    route: string;
}
export type Slug = string;
export interface BookingInput {
    stayId?: Id;
    trekId?: Id;
    name: string;
    travelDates: string;
    email: string;
    yatraId?: Id;
    amountINR: bigint;
    phone: string;
    groupSize: bigint;
    packageId?: Id;
}
export interface SearchResults {
    treks: Array<Trek>;
    packages: Array<Package>;
    blogPosts: Array<BlogPost>;
    stays: Array<Stay>;
    yatras: Array<Yatra>;
}
export interface Trek {
    id: Id;
    region: string;
    durationDays: bigint;
    durationNights: bigint;
    difficulty: string;
    name: string;
    slug: Slug;
    description: string;
    inclusions: Array<string>;
    highlights: Array<string>;
    priceRange: PriceRange;
    state: string;
    imageUrl: string;
    distanceKm: number;
    maxAltitudeM: bigint;
    exclusions: Array<string>;
    category: string;
    endPoint: string;
    maxAltitudeFt: bigint;
    startPoint: string;
    itinerary: Array<DayItinerary>;
    bestSeason: string;
}
export interface BookingWithPaymentResult {
    bookingId: string;
    razorpayOrder: RazorpayOrderResult;
}
export interface Package {
    id: Id;
    tiers: Array<PackageTier>;
    duration: string;
    accommodationType: string;
    name: string;
    slug: Slug;
    description: string;
    inclusions: Array<string>;
    priceRange: PriceRange;
    imageUrl: string;
    groupSizeMax: bigint;
    exclusions: Array<string>;
    category: string;
    groupSize: string;
    itinerary: Array<DayItinerary>;
    problemSolved: string;
}
export interface RazorpayOrderResult {
    orderId: string;
    currency: string;
    amount: bigint;
    keyId: string;
}
export interface PriceRange {
    minINR: bigint;
    maxINR: bigint;
}
export interface PackageTier {
    name: string;
    pricePerPerson: bigint;
}
export type Id = bigint;
export interface Yatra {
    id: Id;
    spiritualSignificance: string;
    duration: string;
    helicopterInfo?: string;
    temples: Array<string>;
    registration: string;
    name: string;
    slug: Slug;
    description: string;
    season: string;
    priceRange: PriceRange;
    permits: string;
    imageUrl: string;
    pujaGuide: string;
    templeTimings: string;
    registrationInfo: string;
    itinerary: Array<DayItinerary>;
    route: string;
    accessibility: string;
}
export interface Stay {
    id: Id;
    nearbyAttractions: Array<string>;
    ownerNote: string;
    pricePerNightMax: bigint;
    pricePerNightMin: bigint;
    stayType: string;
    name: string;
    slug: Slug;
    description: string;
    amenities: Array<string>;
    imageUrl: string;
    location: string;
}
export interface Booking {
    id: Id;
    status: BookingStatus;
    stayId?: Id;
    paymentStatus: string;
    trekId?: Id;
    name: string;
    createdAt: Timestamp;
    travelDates: string;
    email: string;
    razorpaySignature?: string;
    yatraId?: Id;
    razorpayOrderId?: string;
    paymentId?: string;
    amountINR: bigint;
    phone: string;
    groupSize: bigint;
    packageId?: Id;
}
export enum BookingStatus {
    cancelled = "cancelled",
    pending = "pending",
    completed = "completed",
    confirmed = "confirmed"
}
export interface backendInterface {
    confirmBookingPayment(bookingId: bigint, paymentId: string, razorpaySignature: string): Promise<Booking | null>;
    createBooking(input: BookingInput): Promise<Booking>;
    createBookingWithPayment(input: BookingInput): Promise<BookingWithPaymentResult>;
    getAllBlogPosts(): Promise<Array<BlogPost>>;
    getAllBookings(): Promise<Array<Booking>>;
    getAllPackages(): Promise<Array<Package>>;
    getAllStays(): Promise<Array<Stay>>;
    getAllTreks(): Promise<Array<Trek>>;
    getAllYatras(): Promise<Array<Yatra>>;
    getBlogPostBySlug(slug: string): Promise<BlogPost | null>;
    getPackageBySlug(slug: string): Promise<Package | null>;
    getStayBySlug(slug: string): Promise<Stay | null>;
    getTrekBySlug(slug: string): Promise<Trek | null>;
    getTreksByDifficulty(difficulty: string): Promise<Array<Trek>>;
    getTreksByState(state: string): Promise<Array<Trek>>;
    getUserBookings(userEmail: string): Promise<Array<Booking>>;
    getYatraBySlug(slug: string): Promise<Yatra | null>;
    searchAll(searchTerm: string): Promise<SearchResults>;
    searchTreks(searchTerm: string): Promise<Array<Trek>>;
    setRazorpayKeys(keyId: string, secret: string): Promise<void>;
}
import type { BlogPost as _BlogPost, Booking as _Booking, BookingInput as _BookingInput, BookingStatus as _BookingStatus, DayItinerary as _DayItinerary, Id as _Id, Package as _Package, PriceRange as _PriceRange, SearchResults as _SearchResults, Slug as _Slug, Stay as _Stay, Timestamp as _Timestamp, Trek as _Trek, Yatra as _Yatra } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async confirmBookingPayment(arg0: bigint, arg1: string, arg2: string): Promise<Booking | null> {
        if (this.processError) {
            try {
                const result = await this.actor.confirmBookingPayment(arg0, arg1, arg2);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.confirmBookingPayment(arg0, arg1, arg2);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async createBooking(arg0: BookingInput): Promise<Booking> {
        if (this.processError) {
            try {
                const result = await this.actor.createBooking(to_candid_BookingInput_n8(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Booking_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBooking(to_candid_BookingInput_n8(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Booking_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async createBookingWithPayment(arg0: BookingInput): Promise<BookingWithPaymentResult> {
        if (this.processError) {
            try {
                const result = await this.actor.createBookingWithPayment(to_candid_BookingInput_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBookingWithPayment(to_candid_BookingInput_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getAllBlogPosts(): Promise<Array<BlogPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBlogPosts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBlogPosts();
            return result;
        }
    }
    async getAllBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBookings();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBookings();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPackages(): Promise<Array<Package>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPackages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPackages();
            return result;
        }
    }
    async getAllStays(): Promise<Array<Stay>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStays();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStays();
            return result;
        }
    }
    async getAllTreks(): Promise<Array<Trek>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTreks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTreks();
            return result;
        }
    }
    async getAllYatras(): Promise<Array<Yatra>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllYatras();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllYatras();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBlogPostBySlug(arg0: string): Promise<BlogPost | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlogPostBySlug(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlogPostBySlug(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPackageBySlug(arg0: string): Promise<Package | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPackageBySlug(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPackageBySlug(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStayBySlug(arg0: string): Promise<Stay | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStayBySlug(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStayBySlug(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTrekBySlug(arg0: string): Promise<Trek | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrekBySlug(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrekBySlug(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTreksByDifficulty(arg0: string): Promise<Array<Trek>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTreksByDifficulty(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTreksByDifficulty(arg0);
            return result;
        }
    }
    async getTreksByState(arg0: string): Promise<Array<Trek>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTreksByState(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTreksByState(arg0);
            return result;
        }
    }
    async getUserBookings(arg0: string): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserBookings(arg0);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserBookings(arg0);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getYatraBySlug(arg0: string): Promise<Yatra | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getYatraBySlug(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getYatraBySlug(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchAll(arg0: string): Promise<SearchResults> {
        if (this.processError) {
            try {
                const result = await this.actor.searchAll(arg0);
                return from_candid_SearchResults_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchAll(arg0);
            return from_candid_SearchResults_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchTreks(arg0: string): Promise<Array<Trek>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchTreks(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchTreks(arg0);
            return result;
        }
    }
    async setRazorpayKeys(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setRazorpayKeys(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setRazorpayKeys(arg0, arg1);
            return result;
        }
    }
}
function from_candid_BookingStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingStatus): BookingStatus {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Booking_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Booking): Booking {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_SearchResults_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SearchResults): SearchResults {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Yatra_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Yatra): Yatra {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Booking]): Booking | null {
    return value.length === 0 ? null : from_candid_Booking_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BlogPost]): BlogPost | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Package]): Package | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Stay]): Stay | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Trek]): Trek | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Yatra]): Yatra | null {
    return value.length === 0 ? null : from_candid_Yatra_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Id]): Id | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _Id;
    spiritualSignificance: string;
    duration: string;
    helicopterInfo: [] | [string];
    temples: Array<string>;
    registration: string;
    name: string;
    slug: _Slug;
    description: string;
    season: string;
    priceRange: _PriceRange;
    permits: string;
    imageUrl: string;
    pujaGuide: string;
    templeTimings: string;
    registrationInfo: string;
    itinerary: Array<_DayItinerary>;
    route: string;
    accessibility: string;
}): {
    id: Id;
    spiritualSignificance: string;
    duration: string;
    helicopterInfo?: string;
    temples: Array<string>;
    registration: string;
    name: string;
    slug: Slug;
    description: string;
    season: string;
    priceRange: PriceRange;
    permits: string;
    imageUrl: string;
    pujaGuide: string;
    templeTimings: string;
    registrationInfo: string;
    itinerary: Array<DayItinerary>;
    route: string;
    accessibility: string;
} {
    return {
        id: value.id,
        spiritualSignificance: value.spiritualSignificance,
        duration: value.duration,
        helicopterInfo: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.helicopterInfo)),
        temples: value.temples,
        registration: value.registration,
        name: value.name,
        slug: value.slug,
        description: value.description,
        season: value.season,
        priceRange: value.priceRange,
        permits: value.permits,
        imageUrl: value.imageUrl,
        pujaGuide: value.pujaGuide,
        templeTimings: value.templeTimings,
        registrationInfo: value.registrationInfo,
        itinerary: value.itinerary,
        route: value.route,
        accessibility: value.accessibility
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    treks: Array<_Trek>;
    packages: Array<_Package>;
    blogPosts: Array<_BlogPost>;
    stays: Array<_Stay>;
    yatras: Array<_Yatra>;
}): {
    treks: Array<Trek>;
    packages: Array<Package>;
    blogPosts: Array<BlogPost>;
    stays: Array<Stay>;
    yatras: Array<Yatra>;
} {
    return {
        treks: value.treks,
        packages: value.packages,
        blogPosts: value.blogPosts,
        stays: value.stays,
        yatras: from_candid_vec_n11(_uploadFile, _downloadFile, value.yatras)
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _Id;
    status: _BookingStatus;
    stayId: [] | [_Id];
    paymentStatus: string;
    trekId: [] | [_Id];
    name: string;
    createdAt: _Timestamp;
    travelDates: string;
    email: string;
    razorpaySignature: [] | [string];
    yatraId: [] | [_Id];
    razorpayOrderId: [] | [string];
    paymentId: [] | [string];
    amountINR: bigint;
    phone: string;
    groupSize: bigint;
    packageId: [] | [_Id];
}): {
    id: Id;
    status: BookingStatus;
    stayId?: Id;
    paymentStatus: string;
    trekId?: Id;
    name: string;
    createdAt: Timestamp;
    travelDates: string;
    email: string;
    razorpaySignature?: string;
    yatraId?: Id;
    razorpayOrderId?: string;
    paymentId?: string;
    amountINR: bigint;
    phone: string;
    groupSize: bigint;
    packageId?: Id;
} {
    return {
        id: value.id,
        status: from_candid_BookingStatus_n4(_uploadFile, _downloadFile, value.status),
        stayId: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.stayId)),
        paymentStatus: value.paymentStatus,
        trekId: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.trekId)),
        name: value.name,
        createdAt: value.createdAt,
        travelDates: value.travelDates,
        email: value.email,
        razorpaySignature: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.razorpaySignature)),
        yatraId: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.yatraId)),
        razorpayOrderId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.razorpayOrderId)),
        paymentId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.paymentId)),
        amountINR: value.amountINR,
        phone: value.phone,
        groupSize: value.groupSize,
        packageId: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.packageId))
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    confirmed: null;
}): BookingStatus {
    return "cancelled" in value ? BookingStatus.cancelled : "pending" in value ? BookingStatus.pending : "completed" in value ? BookingStatus.completed : "confirmed" in value ? BookingStatus.confirmed : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Booking>): Array<Booking> {
    return value.map((x)=>from_candid_Booking_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Yatra>): Array<Yatra> {
    return value.map((x)=>from_candid_Yatra_n12(_uploadFile, _downloadFile, x));
}
function to_candid_BookingInput_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingInput): _BookingInput {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    stayId?: Id;
    trekId?: Id;
    name: string;
    travelDates: string;
    email: string;
    yatraId?: Id;
    amountINR: bigint;
    phone: string;
    groupSize: bigint;
    packageId?: Id;
}): {
    stayId: [] | [_Id];
    trekId: [] | [_Id];
    name: string;
    travelDates: string;
    email: string;
    yatraId: [] | [_Id];
    amountINR: bigint;
    phone: string;
    groupSize: bigint;
    packageId: [] | [_Id];
} {
    return {
        stayId: value.stayId ? candid_some(value.stayId) : candid_none(),
        trekId: value.trekId ? candid_some(value.trekId) : candid_none(),
        name: value.name,
        travelDates: value.travelDates,
        email: value.email,
        yatraId: value.yatraId ? candid_some(value.yatraId) : candid_none(),
        amountINR: value.amountINR,
        phone: value.phone,
        groupSize: value.groupSize,
        packageId: value.packageId ? candid_some(value.packageId) : candid_none()
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
